[build]
command = "npm ci && hugo --minify --gc -b $URL"
# use the command below for multilingual sites which enable "defaultContentLanguageInSubdir",
# to set up the fallback 404 page, please replace the en with your default language as well.
# command = "npm ci && hugo --minify --gc -b $URL && cp public/en/404.html public/404.html"
publish = "public"

[build.environment]
NODE_VERSION = "19"
HUGO_VERSION = "0.111.3"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
GO_VERSION = "1.20"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

# multilingual 404 pages, remove it on monolingual sites.
[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404
