hb:
  blog:
    paginate: 12
    post_date_format: ":date_long"
    post_thumbnail: true
    post_thumbnail_default: "images/thumbnail.png"
    post_thumbnail_placeholder: ""
    home:
      featured_posts: 5
      main_sections:
        - docs
        - blog
    archives:
      paginate: 30
